version: "3"
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "10008:3001"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
