name: prod workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run:
    # The type of runner that the job will run on
    runs-on:
      - self-hosted
      - louis-server

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Run the prod docker-compose
        env:
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          touch server/.env
          echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> server/.env
          echo DATABASE_USER=basic >> server/.env
          echo DATABASE_HOST=127.0.0.1 >> server/.env
          echo DATABASE_PORT=10013 >> server/.env
          echo DATABASE_NAME=agora >> server/.env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> server/.env
          echo VAPID_PRIVATE_KEY=${{ secrets.VAPID_PRIVATE_KEY }} >> server/.env
          echo VAPID_PUBLIC_KEY=BGIz7gLeHDXxdt7TkmRCUT-jK9U28FC7DHHBDJoi841yPVdTuKUKf6H7vpWR3UUfWA-YqrmDTijUVDSHA3YuJ0Q >> server/.env
          docker-compose up --build -d
